// File generated by FlutterFire CLI with dummy placeholder values so the app won't crash on startup.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'dummy-api-key-web',
    appId: '1:1234567890:web:12abc345def67890',
    messagingSenderId: '1234567890',
    projectId: 'vitaltrack-dummy',
    authDomain: 'vitaltrack-dummy.firebaseapp.com',
    storageBucket: 'vitaltrack-dummy.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'dummy-api-key-android',
    appId: '1:1234567890:android:12abc345def67890',
    messagingSenderId: '1234567890',
    projectId: 'vitaltrack-dummy',
    storageBucket: 'vitaltrack-dummy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'dummy-api-key-ios',
    appId: '1:1234567890:ios:12abc345def67890',
    messagingSenderId: '1234567890',
    projectId: 'vitaltrack-dummy',
    storageBucket: 'vitaltrack-dummy.appspot.com',
    iosBundleId: 'com.example.vitaltrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'dummy-api-key-macos',
    appId: '1:1234567890:ios:12abc345def67890',
    messagingSenderId: '1234567890',
    projectId: 'vitaltrack-dummy',
    storageBucket: 'vitaltrack-dummy.appspot.com',
    iosBundleId: 'com.example.vitaltrack.RunnerTests',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'dummy-api-key-windows',
    appId: '1:1234567890:web:12abc345def67890',
    messagingSenderId: '1234567890',
    projectId: 'vitaltrack-dummy',
    authDomain: 'vitaltrack-dummy.firebaseapp.com',
    storageBucket: 'vitaltrack-dummy.appspot.com',
  );
}
